services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: toptry
      POSTGRES_PASSWORD: toptry
      POSTGRES_DB: toptry
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - toptry_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - toptry_redis:/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - "127.0.0.1:9000:9000" # S3 API
      - "127.0.0.1:9001:9001" # Console
    volumes:
      - toptry_minio:/data


volumes:
  toptry_pg:
  toptry_redis:
  toptry_minio:
